spring:
  application.name: order-service
  sleuth.sampler.percentage: 1
  jpa:
    database-platform: H2
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server.port: 9004

logging.level:
  com.netflix.eureka: error
