spring.application.name: config-service
server.port: 8888

spring.cloud.config.server.git.uri: file://${user.home}/config-repo

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level:
  com.netflix.eureka: error
